# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/deannanicdao/pomodoro_ruby_app" }

# gem "rails"

gem "rspec", "~> 3.9"
gem 'ruby2d'
gem 'pastel'
gem 'colorize'
gem 'tty-prompt'
gem 'tty-font'